name: Docker build and push

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 13 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build the image
        id: build
        run: |
          LATEST_TAG=$(git ls-remote --tags origin |awk -F \/ '{print $NF}'|sort -Vr|head -1)
          NEXT_TAG=$(docker run --rm alpine/semver:latest semver -c -i patch ${LATEST_TAG})
          echo "::set-output name=tag::$NEXT_TAG"

          GIT_REPORTED_VERSION=$(docker build . --no-cache | grep "Installing git" | awk -F '[()]' '{print $4}')
          GIT_FULL_VERSION=$(docker run --rm alpine/semver:latest semver -c ${GIT_REPORTED_VERSION}) 
          GIT_MAJOR_MINOR_VERSION=${GIT_FULL_VERSION%.*}
          GIT_MAJOR_VERSION=${GIT_FULL_VERSION%.*.*}

          GIT_FULL_VERSION=$GIT_FULL_VERSION GIT_MAJOR_VERSION=$GIT_MAJOR_VERSION GIT_MAJOR_MINOR_VERSION=$GIT_MAJOR_MINOR_VERSION docker buildx bake --push

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{steps.build.outputs.tag}}"
